### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Griffin1110** [thecraptheorist/eve#1]
So I did the thing and it is not giving me free money 
This doesn’t work
Bad framework

**Comment by thecraptheorist** [comment]
hi this is microsoft technical support here:
the owner of this repository wishes to let you know that its not meant for you to work
its only meant to work for him

**Comment by Griffin1110** [comment]
I was told if I pay 99999999 dollars I can get this fixed, I shall put a complaint with the Australian scamwatch commitee

**Comment by thecraptheorist** [comment]
not happening

**Comment by Griffin1110** [comment]
you seem salt

**Comment by thecraptheorist** [comment]
how do you restrict people from commenting on stuff

**Comment by thecraptheorist** [comment]
oooo interestinggg
